### ISSUE TITLE
Publish to official Terraform module registry

### ISSUE THREAD

**Issue by Clete2** [StateFarmIns/terraform-aws-quicksight-user-pruning#3]
https://www.terraform.io/registry/modules/publish

**Comment by KarlKeisel** [comment]
No good examples of CI CD for auto publishing modules found as of yet, however did find a github action that seems to do what we want.

https://github.com/TakeScoop/publish-terraform-cloud-module-action

**Comment by KarlKeisel** [comment]
First time done manually, then Terraform will be automatically updated when a new tag comes out.
